import { expect, test } from '@playwright/test';
import { gotoAndWait, readBrowserIngredients, seedBrowserState } from './support/testApp';

test('actual received amount refreshes shortages and remains after the dinner is skipped', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.clock.setFixedTime(new Date('2026-09-16T08:00:00.000Z'));
  await seedBrowserState(page, { ingredients: [] });
  await gotoAndWait(page, '/meal-plan');
  await page.getByLabel('주 시작일').fill('2026-09-21');
  await page.getByLabel('식사 인원').selectOption('2');
  for (const name of ['화요일', '수요일', '목요일', '금요일', '토요일', '일요일']) await page.getByRole('checkbox', { name: `${name} 저녁`, exact: true }).uncheck();
  await page.getByLabel('피하고 싶은 재료').fill('파스타면, 소면, 쌀, 중화면, 계란, 두부, 닭고기, 김치, 참치캔, 돼지고기, 소고기');
  await page.getByRole('button', { name: '한 주 식단 만들기' }).click();
  const monday = page.getByRole('article', { name: '2026-09-21 저녁 식단' });
  await expect(monday.getByRole('heading', { name: '시금치 리조또', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '이 식단 확정', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '이 식단 확정', exact: true }).click();
  await expect(page.getByText('확정됨', { exact: true })).toBeVisible();
  const preview = page.getByRole('region', { name: '식단 장보기 미리보기' });
  await preview.getByRole('button', { name: '식단 장보기 확인', exact: true }).click();
  await expect(preview.getByText('360g', { exact: true })).toBeVisible();
  const notes = page.getByRole('region', { name: '장보기 메모', exact: true });
  await notes.getByRole('button', { name: '장보기 메모 열기', exact: true }).click();
  const manual = notes.getByRole('form', { name: '수동 장보기 추가', exact: true });
  await manual.getByLabel('품목 이름', { exact: true }).fill('우유');
  await manual.getByLabel('필요량 메모', { exact: true }).fill('한 통');
  await manual.getByRole('button', { name: '수동 항목 추가', exact: true }).click();
  await expect(notes.getByText('수동 항목을 저장했어요.', { exact: true })).toBeVisible();
  const purchase = notes.getByRole('form', { name: '구매 메모 작성' });
  await purchase.getByLabel('구매한 품목의 출처').selectOption({ label: '식단: 밥 (360g)' });
  await purchase.getByLabel('실제로 산 양', { exact: true }).fill('500g 한 팩');
  await purchase.getByRole('button', { name: '구매 메모 저장' }).click();
  await expect(notes.getByText('구매 메모를 저장했어요.', { exact: true })).toBeVisible();
  expect(await readBrowserIngredients(page, 'guest')).toEqual([]);
  const history = notes.getByRole('region', { name: '구매 메모 이력', exact: true });
  await history.getByText('입고할 양 확인', { exact: true }).click();
  const receive = history.getByRole('form', { name: '구매 반영 · 밥', exact: true });
  await expect(receive.getByLabel('확인한 구매량', { exact: true })).toHaveValue('');
  await receive.getByLabel('확인한 구매량', { exact: true }).fill('500');
  await receive.getByLabel('입고 상태', { exact: true }).selectOption('cooked');
  await receive.getByLabel('보관 장소', { exact: true }).selectOption('냉장');
  await receive.getByLabel('유통기한(모르면 비워두기)', { exact: true }).fill('2026-09-23');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await receive.screenshot({ path: testInfo.outputPath('receipt-form-mobile.png') });
  await receive.getByRole('button', { name: '확인한 구매량을 재고에 반영' }).click();
  await expect(history.getByText('입고 당시 500g · 현재 남은 양은 냉장고에서 확인해 주세요.', { exact: true })).toBeVisible();
  // The already-open calculation must be invalidated by physical receiving.
  await expect(preview.getByRole('button', { name: '식단 장보기 확인', exact: true })).toBeVisible();
  await expect(preview.getByText('360g', { exact: true })).toHaveCount(0);
  await preview.getByRole('button', { name: '식단 장보기 확인', exact: true }).click();
  await expect(preview.getByRole('list', { name: '확인된 부족분', exact: true }).getByText('밥', { exact: true })).toHaveCount(0);
  const stock = await readBrowserIngredients(page, 'guest');
  expect(stock).toHaveLength(1);
  expect(stock[0]).toMatchObject({ name: '밥', quantity: '500g 한 팩', consumed: false });
  await monday.getByRole('button', { name: '외식·건너뛰기', exact: true }).click();
  await expect(page.getByRole('button', { name: '수정 초안으로 확정본 교체', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: '수정 초안으로 확정본 교체', exact: true }).click();
  await expect(page.getByText('확정됨', { exact: true })).toBeVisible();
  await page.reload();
  await page.getByLabel('주 시작일').fill('2026-09-21');
  await notes.getByRole('button', { name: '장보기 메모 열기', exact: true }).click();
  await expect(notes.getByRole('form', { name: '우유 수동 항목', exact: true })).toBeVisible();
  await expect(history.getByText('입고 당시 500g · 현재 남은 양은 냉장고에서 확인해 주세요.', { exact: true })).toBeVisible();
  await expect(history.getByText('기록 당시 필요량: 360g', { exact: true })).toBeVisible();
  await expect(history.getByText('입고할 양 확인', { exact: true })).toHaveCount(0);
  expect(await readBrowserIngredients(page, 'guest')).toEqual(stock);
  await history.screenshot({ path: testInfo.outputPath('receipt-history-mobile.png') });
  await gotoAndWait(page, '/ingredients');
  await expect(page.getByRole('heading', { name: '밥', exact: true })).toBeVisible();
  const quantities = page.getByRole('region', { name: '남은 수량 확인', exact: true });
  await quantities.getByRole('button', { name: '수량 확인 목록 열기', exact: true }).click();
  await expect(quantities.getByRole('form', { name: '밥 남은 수량 확인', exact: true }).getByLabel('확인한 남은 양', { exact: true })).toHaveValue('500');
});
